volumes:
  v49_resources:
  v49_redis:
  v49_assets:

services:
  romm-v49:
    image: ghcr.io/rommapp/romm:4.9.2
    container_name: romm-v49
    restart: unless-stopped
    environment:
      - DB_HOST=romm-testbed-db
      - DB_NAME=romm_v49
      - DB_USER=${DB_USER}
      - DB_PASSWD=${DB_PASSWORD}
      - ROMM_AUTH_SECRET_KEY=${ROMM_AUTH_SECRET_KEY}
      - HASHEOUS_API_ENABLED=true
    volumes:
      - v49_resources:/romm/resources
      - v49_redis:/redis-data
      - v49_assets:/romm/assets
      - ${TESTBED_LIBRARY}:/romm/library:ro
    ports:
      - "8091:8080"
    depends_on:
      romm-testbed-db:
        condition: service_healthy
        restart: true
